pipeline:
  build:
    image: plugins/docker
    secrets: [docker_username, docker_password, docker_registry]
    registry: ${DOCKER_REGISTRY}:2087
    repo: ${DOCKER_REGISTRY}:2087/testnet/node
    tags: latest
    when:
      branch:
        - Dev
      event:
        - push
        - tag
  notify-build:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    when:
      branch:
        - Dev
      status:
        - success
        - failure
      event:
        - push
        - tag
  deploy-bootnode-dev:
    image: peloton/drone-rancher
    url: https://testnet.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/testnet/node:latest
    service: bootnode/bootnode-dev
    confirm: true
    timeout: 240
    when:
      branch:
        - Dev
      status:
        - success
      event:
        - push
        - tag
  deploy-node-dev:
    image: peloton/drone-rancher
    url: https://testnet.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/testnet/node:latest
    service: node/node-dev
    confirm: true
    timeout: 240
    when:
      branch:
        - Dev
      status:
        - success
      event:
        - push
        - tag
  notify-deploy-dev:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2705 ${DRONE_REPO}:`${DRONE_COMMIT_BRANCH}` ${DRONE_BUILD_NUMBER} deployment successful
    when:
      branch:
        - Dev
      status:
        - success
      event:
        - push
        - tag
