pipeline:
  build:
    image: terrorjack/meikyu:ghc-8.2.2
    commands:
      - "stack --stack-yaml=CI.stack.yaml build"
    when:
      branch:
        - master
  notify-build:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    when:
      status: [ success, failure ]
  publish:
    image: plugins/docker
    secrets: [docker_username, docker_password, docker_repo]
    registry: $DOCKER_REPO:2087
    repo: $DOCKER_REPO:2087/testnet/node
    auto_tag: true
    when:
      branch:
        - master
      status:
        - success
      event:
        - push
        - tag
  deploy-bootnode:
    image: peloton/drone-rancher
    url: https://testnet.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/testnet/node:latest
    service: bootnode/bootnode
    batch_size: 8
    confirm: true
    timeout: 240
  notify-deploy-bootnode:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2705 bootnode deployment successful
    when:
      status: [ success ]
  deploy-node:
    image: peloton/drone-rancher
    url: https://testnet.enecuum.com:2096
    secrets:
      - source: rancher_access_key
        target: PLUGIN_ACCESS_KEY
      - source: rancher_secret_key
        target: PLUGIN_SECRET_KEY
    docker_image: dev.enecuum.com:2087/testnet/node:latest
    service: node/node
    batch_size: 20
    confirm: true
    timeout: 240
  notify-deploy-node:
    image: dev.enecuum.com:2087/library/drone-telegram:v1.0.0
    secrets: [telegram_token, telegram_id]
    message: \u2705 node deployment successful
    when:
      status: [ success ]
