resolver: nightly-2018-10-20

packages:
- .

extra-deps:
- base58-bytestring-0.1.0
- cryptohash-sha256-0.11.101.0
- fmt-0.6
- time-units-1.0.0

build:
  haddock-arguments:
    haddock-args:
    - "--odir=./docs"
